import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

// _id is a special field that is automatically generated by Convex
export default defineSchema({
  posts: defineTable({
    title: v.string(),
    body: v.string(),
    authorId: v.string(),
  }),
});