import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

// _id is a special field that is automatically generated by Convex
export default defineSchema({
  comments: defineTable({
    postId: v.id("posts"),
    body: v.string(),
    authorId: v.string(),
    authorName: v.string(),
  }),
  posts: defineTable({
    title: v.string(),
    body: v.string(),
    authorId: v.string(),
    imageStorageId: v.optional(v.id('_storage')),
  }).searchIndex("search_title", {
    searchField: "title",
  }).searchIndex("search_body", {
    searchField: "body",
  }),
});